### ISSUE TITLE
something strange with isoline

### ISSUE THREAD

**Issue by IMMSPgisgroup** [RaumZeit/MarchingSquares.js#18]
We use data from 
[sampleData.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2298827/sampleData.zip) in version 1.2.1. We use MarchingSquaresJS.isoContours(data, breaks[breakNumber]) with breaks = [0.00005, 0.9]. In result we see three-dimensional arrays like this 
[resultData.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2298850/resultData.zip). We see that isolnes are from one part. Why array is not two-dimensional? That is right?

**Comment by RaumZeit** [comment]
Hi,
I don't see anything strange in the resultData!

The outermost array simply packages all isolines from the computation. Each isoline then is an array of points that define it, while each point consists of two coordinates, x and y.

So yes, in total, you get a 3 dimensional array. Though I would say, you get a list of isolines, i.e. a list of lists of 2D coordinates.

**Comment by IMMSPgisgroup** [comment]
Hi,
Say otherwise. This  three-dimensional array not for many isolines. This for one one-part isoline.
Some samples (about two isolines with values 0.00005 and 0.9 respectively). 
[sample.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2320196/sample.zip)
What we do wrong?

**Comment by RaumZeit** [comment]
Sorry, I can't figure out what you are considering wrong here! Please explain in detail where you get three dimensional arrays and where you don't.

As I said earlier, the array that is returned by the `isoContours()` function is always 3 dimensional, strictly speaking. It might even be four dimensional with the latest version, if the `breaks` input parameter is an array instead of a scalar value...

**Comment by IMMSPgisgroup** [comment]
Some samples with version 1.2.1 and MarchingSquaresJS.isoContours().
[isolines.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2325720/isolines.zip)
[resultIsolines.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2325741/resultIsolines.zip)
Isoline with 0.00005 (scratchpadFirst.js) have something strange.

**Comment by RaumZeit** [comment]
...after thinking about what you actually wanted to tell me, I believe that you were asking for the following:

1. Why is the isoline for value 0.00005 not continuous but rather piece-wise?
2. ... and is this the expected behavior?

The answer to both questions is simple: Yes, this is expected behavior in version 1.2.1 which does not yield linear ring coordinates for the `isoLines()`/`isoContours()` function by default.

In fact, the piece-wise output is an artifact of the line-tracing implementation. It starts scanning the input grid row by row from the left to the right column. Furthermore, each line is considered to enclose an area below the given threshold in a counter-clockwise orientation. Thus, in your example, the first lines in your grid that are processed never exceed two coordinates since in the first row, the tracer hits the grid boundary immediately. Then, in the second row, it tries to continue the path in the first row, which has already been traced, so it stops again. This continues further and further, until a anti-clockwise path can be found at some point.

Note, that the default behavior to return linear ring coordinates was restored with version 1.2.3! Consequently, the isoline for value 0.00005 is a single closed contour in that case. (Though there still is a bug in the latest version that results in two isolines instead, which is only fixed in the `development` branch).

I hope this answers your question! If not, feel free to ask again!

**Comment by IMMSPgisgroup** [comment]
Thank you for your answer.
______________________________
With regard, IMMSPgisgroup

**Comment by RaumZeit** [comment]
Sure!

Btw, I just released version 1.3.2 which fixes the remaining ring coordinate tracing bug. The default settings now return a closed single path iso line for your example again.
