### ISSUE TITLE
Something strange with isoline in version 1.3.2. Incorrect hyperbola ambiguity processing in version 1.2.1.

### ISSUE THREAD

**Issue by IMMSPgisgroup** [RaumZeit/MarchingSquares.js#23]
Data grid - [data](https://github.com/RaumZeit/MarchingSquares.js/files/3077563/bugData.txt).
In version 1.3.2 if 
```javascript
MarchingSquaresJS.isoContours(data, break, options) 
```
with data (height - 35, width - 30), break = 0.1 and options = {"linearRing":false} we obtain something strange.  Obtained isoline - [version1.3.2.geojson.zip](https://github.com/RaumZeit/MarchingSquares.js/files/3077585/version1.3.2.geojson.zip)
![version1 3 2](https://user-images.githubusercontent.com/33963849/56095581-083a3700-5ee7-11e9-96af-e0ed9f9ce33a.jpeg)
 Give recommends for such situation, please. There is no this situation with version 1.2.1. For this reason we use version 1.2.1. But recently we see in this version bug with hyperbola ambiguity processing. In version 1.2.1 if 
```javascript
MarchingSquaresJS.isoContours(data, break) 
```
with data (height - 35, width - 30), break = 0.03 we obtain isoline without one segments in cell with hyperbola ambiguity. 
![version1 2 1](https://user-images.githubusercontent.com/33963849/56095560-e04ad380-5ee6-11e9-8eca-4628a4846d1f.jpeg)
 But in this case must be two segments (obtained isoline - 
[version1.2.1.geojson.zip](https://github.com/RaumZeit/MarchingSquares.js/files/3077587/version1.2.1.geojson.zip)). In version 1.3.2 this bug do not exist.

**Comment by RaumZeit** [comment]
Hi,
the result you obtain from 1.3.2 seems right for me.

There are two areas where your data is above the threshold of 0.1, they are clearly highlighted as such. The enclosing rectangular frame is always added, if there are no data points above the threshold that lie directly at the borders of the input data (I assume this is what you mean by 'something strange').

Note, that the isoLines()/isoContours functions yield paths that enclose the data below the set threshold. That's why you get the enclosing frame as well. Since you disabled the linearRing option, there are just 4 coordinates for the outer frame, hence the frame is not closed in your example. This outer-frame detection was not working correctly in some of the 1.2.x versions, btw.

As a work-around if you really want to drop the outer frame, you could simply detect it in the returned path arrays and discard it manually...

Does that answer your question?

P.S.: I don't support older versions or add bugfixes for them, so please refer to the latest version instead.

**Comment by IMMSPgisgroup** [comment]
> There are two areas where your data is above the threshold of 0.1, they are clearly highlighted as such. The enclosing rectangular frame is always added, if there are no data points above the threshold that lie directly at the borders of the input data (I assume this is what you mean by 'something strange').


Yes, I speaked about this. But what meaning of this enclosing frame  if I need isoline, not isoband? May be, this frame dropping is better realized as one of options, if this not very difficult, of course. As far as I know, that segment joining for results of contouring algorithms is not trivial in some cases. 
P.S. With respect to version 1.2.1, I use it only for reason of exists this rectangles in version 1.3.2 and detected bug in marching squares realisation in verison 1.2.1 (in ambiquity processing).
__________________________________________________________________
With best regards, IMMSPgisgroup

**Comment by RaumZeit** [comment]
Please have a look at [v1.3.3](https://github.com/RaumZeit/MarchingSquares.js/releases/tag/v1.3.3) that I just released.

The `options` object may now contain an additional attribute `noFrame` that allows for deactivating the enclosing frame path in the `isoLines()` / `isoContours()` implementation. This new boolean flag is `false` by default. Setting it to `true` should yield the result you've been expecting in your first example.

**Comment by IMMSPgisgroup** [comment]
Hi,
I checked version 1.3.3 with some examples, and at first sight this version works well with them.
One of this examples (after some smoothing).
![bigGrid](https://user-images.githubusercontent.com/33963849/56970853-bb09c680-6b70-11e9-93b9-40c934326a66.jpeg)
______________
With best regards, IMMSPgisgroup

**Comment by RaumZeit** [comment]
Perfect, I'll close this issue then...
