### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by stebogit** [RaumZeit/MarchingSquares.js#3]
@RaumZeit ,
I noticed you released your code under AGPL, meaning basically it can not be integrated in projects that don't share that same "rigid" license. Your library is probably the only open-source one available not specifically created for computer graphics and image processing, so I believe it would be quite useful in a variety of other projects (like mine).
I was wondering if you would be available to change licensing or maybe releasing a new version under MIT license?
Thank you

**Comment by RaumZeit** [comment]
Hi Stefano,

sorry for the delayed answer. I've been thinking a lot about your question about re-licensing my code. However, when I decided to put this library under AGPL v3 my main intention was that any modifications of this code should be made available back to the community. I have some concerns about non-copyleft licenses, such as MIT, in particular because they allow people to benefit from open source software without being altruistic themselves. But I totally see your point and of course I'm also interested in seeing other projects using my code!

That's why I think of adding an additional clause to the AGPL v3 under Section 7, to allow inclusion of __unmodified__ versions of my library in third-party projects without forcing said third-party project to be subject to any requirement of the AGPL v3. This has been done for many other projects released under AGPL v3 as well, and I think it might be a good compromise between easy integration of my code while still retaining the requirement of contributing back any improvements to the community. (see e.g. http://unitjs.com/license.html or http://webodf.org/about/license.html)

I think such an addition to my license should enable you (and others) to include my library while keeping turf.js (or any other software) unaffected by the strict rules of AGPL v3.

What do you think about that?

**Comment by stebogit** [comment]
Thanks!! I'd say that's a great solution!
However I am not an expert in licensing, so just let me make sure the guys at Turf are ok with that (which it'll mean it'll be ok for my project as well 😄 ).

Also, I needed to load the library with [`webpack`](https://github.com/webpack/webpack) so I made few changes to the code to allowed that. Would it be ok for you to include that feature?
I'd be happy to submit a PR to show you my changes.

Finally I noticed the `polygons: true` option is not actually working, giving an error when calling  `var a = polygon_table[gg.cval](gg);` inside the `BandGrid2Areas` function, reporting that `polygon_table[gg.cval]` it's not a function.
I can create an issue with an example of the code if you like.

Thanks again

**Comment by stebogit** [comment]
Great!
Turf people just confirmed me with the additional clause in your license it would be OK with them to include your library and my code into turf. 
Awesome! 😄

**Comment by RaumZeit** [comment]
Yes, please send me a PR! I think any modification to make my library loadable with things like `webpack` can only be beneficial.
Also, please add an issue such that I can have a look at that problem with `polygons: true`

Best

**Comment by stebogit** [comment]
Sorry, I'll be able to work on this in a couple of weeks.
I'll create it as soon as I can, I promise! 😜

**Comment by RaumZeit** [comment]
No problem, take your time!
The promised change to the license is already available through github (see commit 870f006)

I hope this makes the inclusion of your code to TurfJS easier
