### ISSUE TITLE
Guidelines and limitations of the input grid data?

### ISSUE THREAD

**Issue by maphew** [RaumZeit/MarchingSquares.js#9]
What are the guidelines and practical limitations for the input data?

The index.html example uses an extremely tiny grid of text values, whereas I'd like to use a raster elevation image* at desktop screen resolutions, so in the range of 1,000 to 2,000 rows and columns.  My testing so far has been hit and miss. I've gotten as many as 2,500 rows to work, while at other times under 1,000 has failed. Perhaps something to do with internal data complexity(?)

JS console output when it does fail:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Array.o (d3.v3.min.js:1)
    at Object.ao.min (d3.v3.min.js:3)
    at Object.ao.transpose (d3.v3.min.js:3)
    at matt-test.html:1921
```

If it helps, the scenario I'm looking at is flood hazard modelling. The web page supplies the elevation model and widget controls, and the user asks the page "what would be underwater at n meters?" (see:
https://gis.stackexchange.com/questions/258703/web-page-that-dynamically-draws-contours-at-user-specified-elevation)

_* Specifically: a 16bit geotiff, which is a standard elevation file format in the GIS and remote sensing world. Mentioned here for reference, I can convert to ascii json easily enough if that's a hard limit._

**Comment by RaumZeit** [comment]
I've tested the `IsoBands` and `IsoContours` feature for the latest version 1.2.3 with a 2048x2048 input. Despite the long runtime due to a massive number of different iso-band levels I wanted to display, everything went through and seemed reasonable. I've added a more complex 512x512 grid example, `vienna.html` to the `examples/` directory.

If you find any data grid / iso bands (iso lines) example that fails, do not hesitate to re-open this issue (and maybe provide a gist or something else such that I can reproduce your problems)
